const loginFields = [
  {
    labelText: "Email address",
    labelFor: "email-address",
    id: "email-address",
    name: "email",
    type: "email",
    autoComplete: "email",
    isRequired: true,
    placeholder: "Email address",
  },
  {
    labelText: "Password",
    labelFor: "password",
    id: "password",
    name: "password",
    type: "password",
    autoComplete: "current-password",
    isRequired: true,
    placeholder: "Password",
  },
];

const signupFields = [
  {
    labelText: "school",
    labelFor: "school",
    id: "school",
    name: "school",
    type: "text",
    autoComplete: "school",
    isRequired: true,
    placeholder: "school",
  },
  {
    labelText: "degree",
    labelFor: "degree",
    id: "degree",
    name: "degree",
    type: "number",
    autoComplete: "degree",
    isRequired: true,
    placeholder: "degree",
  },
  {
    labelText: "field",
    labelFor: "field",
    id: "field",
    name: "field",
    type: "text",
    autoComplete: "field",
    isRequired: true,
    placeholder: "field",
  },
  {
    labelText: "first_name",
    labelFor: "first_name",
    id: "first_name",
    name: "first_name",
    type: "text",
    autoComplete: "first_name",
    isRequired: true,
    placeholder: "first name",
  },
  {
    labelText: "last_name",
    labelFor: "last_name",
    id: "last_name",
    name: "last_name",
    type: "text",
    autoComplete: "last_name",
    isRequired: true,
    placeholder: "last name",
  },
  {
    labelText: "Username",
    labelFor: "username",
    id: "username",
    name: "username",
    type: "text",
    autoComplete: "username",
    isRequired: true,
    placeholder: "Username",
  },
  {
    labelText: "Email ",
    labelFor: "email",
    id: "email",
    name: "email",
    type: "email",
    autoComplete: "email",
    isRequired: true,
    placeholder: "Email address",
  },
  {
    labelText: "phone_number ",
    labelFor: "phone_number",
    id: "phone_number",
    name: "phone_number",
    type: "text",
    autoComplete: "phone_number",
    isRequired: true,
    placeholder: "phone number",
  },
  {
    labelText: "Password",
    labelFor: "password1",
    id: "password1",
    name: "password1",
    type: "password",
    autoComplete: "password1",
    isRequired: true,
    placeholder: "Password",
  },
  {
    labelText: "Confirm Password",
    labelFor: "password2",
    id: "password2",
    name: "password2",
    type: "password",
    autoComplete: "password2",
    isRequired: true,
    placeholder: "Confirm Password",
  },
];

export { loginFields, signupFields };
